# Generated by Django 5.0.2 on 2024-03-08 07:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=20, verbose_name="Size"),
                ),
                (
                    "cost",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мерч",
                "verbose_name_plural": "Мерч",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MerchCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория мерча",
                "verbose_name_plural": "Категории мерча",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MerchInApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Quantity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мерч в заявках",
                "verbose_name_plural": "Мерч в заявках",
            },
        ),
        migrations.CreateModel(
            name="Promocode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MerchApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(max_length=50, unique=True, verbose_name="Number"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation time"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merch_applications",
                        to="ambassadors.ambassador",
                        verbose_name="Ambassador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на мерч",
                "verbose_name_plural": "Заявки на мерч",
            },
        ),
    ]
