# Generated by Django 5.0.2 on 2024-02-28 07:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(max_length=50, unique=True, verbose_name="Number"),
                ),
                ("ambassador", models.IntegerField(verbose_name="Ambassador")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Creation time"
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merch_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на мерч",
                "verbose_name_plural": "Заявки на мерч",
            },
        ),
        migrations.CreateModel(
            name="MerchInApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merch_in_applications",
                        to="promo.merchapplication",
                        verbose_name="Application",
                    ),
                ),
                (
                    "merch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merch_in_applications",
                        to="promo.merch",
                        verbose_name="Merch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мерч в заявках",
                "verbose_name_plural": "Мерч в заявках",
            },
        ),
        migrations.AddField(
            model_name="merchapplication",
            name="merch",
            field=models.ManyToManyField(
                related_name="applications",
                through="promo.MerchInApplication",
                to="promo.merch",
                verbose_name="Merch",
            ),
        ),
    ]
