# Generated by Django 5.0.2 on 2024-03-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0001_initial"),
        ("promo", "0002_merchapplication_merchinapplication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchapplication",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merch_applications",
                to="ambassadors.ambassador",
                verbose_name="Ambassador",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promocodes",
                to="ambassadors.ambassador",
                verbose_name="Ambassador",
            ),
        ),
    ]
