# Generated by Django 5.0.2 on 2024-03-06 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0006_remove_ambassador_promocode"),
        ("promo", "0004_remove_merchapplication_ambassador_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchapplication",
            name="promocode",
        ),
        migrations.AddField(
            model_name="promocode",
            name="ambassador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promocodes",
                to="ambassadors.ambassador",
                verbose_name="Ambassador",
            ),
        ),
    ]
