# Generated by Django 5.0.2 on 2024-03-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0005_remove_merchapplication_promocode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merch",
            name="slug",
        ),
    ]
