version: '3.9'

services:

  db:
    image: postgres:15.0-alpine
    container_name: "db"
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  backend:
    build: ./
    container_name: "backend"
    volumes:
      - static_value:/app/static/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0:8000"

  nginx:
    image: nginx:1.25.3-alpine
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static
    restart: always
    depends_on:
      - backend

volumes:
  postgres_value:
  static_value:
