# Generated by Django 5.0.2 on 2024-03-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название платформы"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "Платформа контента",
                "verbose_name_plural": "Платформы контента",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GuideKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название набора тасок"
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор задач для гайда",
                "verbose_name_plural": "Наборы задач для гайдов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GuideStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Статус гайда")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Статус гайда",
                "verbose_name_plural": "Статусы гайдов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GuideTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Photo", "Фотография в мерче"),
                            ("Review", "Отзыв"),
                            ("Content", "Контент"),
                        ],
                        max_length=200,
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача для гайда",
                "verbose_name_plural": "Задачи для гайдов",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewPlatfrom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название платформы"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Платформа для отзыва",
                "verbose_name_plural": "Платформы для отзыва",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "is_guide_content",
                    models.BooleanField(
                        default=False, verbose_name="Контент в рамках гайда"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="content.contentplatform",
                        verbose_name="Платформа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pause", "На паузе"),
                            ("not_started", "Не приступил к прохождению"),
                            ("started", "В процессе прохождения"),
                            ("complete", "Завершен"),
                        ],
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guides",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
                (
                    "guide_kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guides",
                        to="content.guidekit",
                        verbose_name="Набор тасок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гайд",
                "verbose_name_plural": "Гайды",
                "ordering": ["ambassador"],
            },
        ),
        migrations.CreateModel(
            name="GuideTaskGuideKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guide_kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.guidekit",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.guidetask",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guidekit",
            name="tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="guide_kits",
                through="content.GuideTaskGuideKit",
                to="content.guidetask",
            ),
        ),
        migrations.CreateModel(
            name="MerchPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="content/", verbose_name="Фото в мерче"
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merch_photos",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография в мерче",
                "verbose_name_plural": "Фотограции в мерче",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="ambassadors.ambassador",
                        verbose_name="Амбассадор",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="content.reviewplatfrom",
                        verbose_name="Платформа",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Отзыв",),
                "verbose_name_plural": "Отзывы",
                "ordering": ["id"],
            },
        ),
    ]
