# Generated by Django 5.0.2 on 2024-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="guide",
            name="task_count",
            field=models.IntegerField(default=0),
        ),
    ]
