# Generated by Django 5.0.2 on 2024-03-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_guidekit_tasks_alter_guidetask_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewplatfrom",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
