# Generated by Django 5.0.2 on 2024-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_guide_counter_alter_guide_task_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["-created"],
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
        migrations.AlterModelOptions(
            name="guide",
            options={
                "ordering": ["ambassador"],
                "verbose_name": "Гайд",
                "verbose_name_plural": "Гайды",
            },
        ),
        migrations.AlterModelOptions(
            name="guidetask",
            options={
                "ordering": ["id"],
                "verbose_name": "Задача для гайда",
                "verbose_name_plural": "Задачи для гайдов",
            },
        ),
        migrations.RemoveField(
            model_name="guidetask",
            name="name",
        ),
        migrations.AlterField(
            model_name="guidetask",
            name="type",
            field=models.CharField(
                choices=[
                    ("Photo", "Фотография в мерче"),
                    ("Review", "Отзыв"),
                    ("Content", "Контент"),
                ],
                max_length=200,
                verbose_name="Тип",
            ),
        ),
    ]
