# Generated by Django 5.0.2 on 2024-03-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0001_initial"),
        ("content", "0003_alter_content_options_alter_guide_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guide",
            name="status",
        ),
        migrations.AddField(
            model_name="guide",
            name="is_pause",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="merchphoto",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merch_photos",
                to="ambassadors.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
    ]
