# Generated by Django 5.0.2 on 2024-03-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0001_initial"),
        ("content", "0004_remove_guide_status_guide_is_pause_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guide",
            name="counter",
        ),
        migrations.RemoveField(
            model_name="guide",
            name="is_pause",
        ),
        migrations.RemoveField(
            model_name="guide",
            name="task_count",
        ),
        migrations.AddField(
            model_name="guide",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pause", "На паузе"),
                    ("not_started", "Не приступил к прохождению"),
                    ("started", "В процессе прохождения"),
                    ("complete", "Завершен"),
                ],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="ambassadors.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="guide_kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guides",
                to="content.guidekit",
                verbose_name="Набор тасок",
            ),
        ),
    ]
