# Generated by Django 5.0.2 on 2024-03-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_rename_reviewplatfrom_reviewplatform_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="platform",
        ),
    ]
