# Generated by Django 5.0.2 on 2024-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_content_platform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContentPlatform",
        ),
        migrations.AddField(
            model_name="content",
            name="image",
            field=models.ImageField(default="None", upload_to="content/"),
        ),
        migrations.AddField(
            model_name="content",
            name="platform",
            field=models.CharField(max_length=200, null=True, verbose_name="Платформа"),
        ),
        migrations.AddField(
            model_name="content",
            name="type",
            field=models.CharField(
                choices=[("review", "Отзыв"), ("content", "Контент")],
                max_length=200,
                null=True,
                verbose_name="Тип (отзыв/контент)",
            ),
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="ReviewPlatform",
        ),
    ]
