# Generated by Django 5.0.2 on 2024-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_delete_contentplatform_content_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="link",
            field=models.URLField(max_length=5000, verbose_name="Ссылка"),
        ),
    ]
