# Generated by Django 5.0.2 on 2024-03-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_content_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["created"],
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
    ]
