# Generated by Django 5.0.2 on 2024-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_content_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["-created"],
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
        migrations.AddField(
            model_name="content",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                default="None", upload_to="content/", verbose_name="Изображение"
            ),
        ),
    ]
