# Generated by Django 5.0.2 on 2024-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_content_options_content_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True,
                default="None",
                null=True,
                upload_to="content/",
                verbose_name="Изображение",
            ),
        ),
    ]
