# Generated by Django 5.0.2 on 2024-03-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_alter_content_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="comment",
        ),
    ]
