# Generated by Django 5.0.2 on 2024-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ROLE 1", "Менеджер"), ("ROLE 2", "Амбассадор")],
                default="ROLE 1",
                max_length=150,
                verbose_name="Роль",
            ),
        ),
    ]
