# Generated by Django 5.0.2 on 2024-03-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=75, unique=True, verbose_name="Slug"),
                ),
                (
                    "name",
                    models.CharField(max_length=75, verbose_name="Цель Амбассадорства"),
                ),
            ],
            options={
                "verbose_name": "Активность",
                "verbose_name_plural": "Активности",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(max_length=6, verbose_name="Индекс")),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                ("street", models.CharField(max_length=50, verbose_name="Улица")),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.CreateModel(
            name="AmbassadorActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=75, unique=True, verbose_name="Slug"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=75, verbose_name="Программа в Практикуме"
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
            },
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=75, unique=True, verbose_name="Slug"),
                ),
                (
                    "name",
                    models.CharField(max_length=75, verbose_name="Цель в Практикуме"),
                ),
                (
                    "personal_purpose",
                    models.TextField(
                        blank=True, null=True, verbose_name="Moя цель в Практикуме"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цели",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=75, unique=True, verbose_name="Slug"),
                ),
                ("name", models.CharField(max_length=75, verbose_name="Статус")),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ФИО")),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужской"), ("Ж", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "clothing_size",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                        ],
                        max_length=2,
                        verbose_name="Размер одежды",
                    ),
                ),
                (
                    "shoe_size",
                    models.CharField(max_length=4, verbose_name="Размер обуви"),
                ),
                (
                    "education",
                    models.CharField(max_length=120, verbose_name="Образование"),
                ),
                ("job", models.CharField(max_length=120, verbose_name="Место работы")),
                ("email", models.EmailField(max_length=30, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=30, verbose_name="Telegram"),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="Whatsapp"
                    ),
                ),
                (
                    "blog_link",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ссылка на блог",
                    ),
                ),
                ("onboarding_status", models.BooleanField(default=True)),
                (
                    "about_me",
                    models.TextField(blank=True, null=True, verbose_name="О себе"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ambassadors",
                        to="ambassadors.address",
                        verbose_name="Адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Амбассадор",
                "verbose_name_plural": "Амбассадоры",
            },
        ),
    ]
