# Generated by Django 5.0.2 on 2024-02-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(max_length=6)),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.CreateModel(
            name="GroupPurposeProgramStatusBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужской"), ("Ж", "Женский")], max_length=1
                    ),
                ),
                ("clothing_size", models.CharField(max_length=2)),
                ("shoe_size", models.CharField(max_length=4)),
                ("education", models.CharField(max_length=120)),
                ("job", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=30)),
                ("phone_number", models.CharField(max_length=14)),
                ("telegram_id", models.CharField(max_length=30)),
                ("whatsapp", models.CharField(blank=True, max_length=14, null=True)),
                ("activity", models.CharField(max_length=255)),
                ("blog_link", models.URLField(blank=True, max_length=255, null=True)),
                ("tutor", models.IntegerField(default=0)),
                ("onbording_status", models.BooleanField(default=True)),
                ("about_me", models.TextField(blank=True, null=True)),
                ("promocode", models.IntegerField(default=0)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ambassadors",
                        to="ambassadors.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Амбассадор",
                "verbose_name_plural": "Амбассадоры",
            },
        ),
        migrations.CreateModel(
            name="AmbassadorMerch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merch", models.IntegerField(default=0)),
                ("amount_of_shipments", models.IntegerField()),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Merch",
                        to="ambassadors.ambassador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "grouppurposeprogramstatusbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ambassadors.grouppurposeprogramstatusbase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
            bases=("ambassadors.grouppurposeprogramstatusbase",),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "grouppurposeprogramstatusbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ambassadors.grouppurposeprogramstatusbase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
            },
            bases=("ambassadors.grouppurposeprogramstatusbase",),
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "grouppurposeprogramstatusbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ambassadors.grouppurposeprogramstatusbase",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цели",
            },
            bases=("ambassadors.grouppurposeprogramstatusbase",),
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "grouppurposeprogramstatusbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ambassadors.grouppurposeprogramstatusbase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
            bases=("ambassadors.grouppurposeprogramstatusbase",),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.program",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="purpose",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.purpose",
            ),
        ),
        migrations.AddField(
            model_name="ambassador",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.status",
            ),
        ),
    ]
