# Generated by Django 5.0.2 on 2024-03-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="onboarding_status",
            field=models.BooleanField(default=False, verbose_name="Onboarding статус"),
        ),
    ]
