# Generated by Django 5.0.2 on 2024-03-06 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ambassadors",
            "0002_alter_ambassador_promocode_alter_ambassador_tutor_and_more",
        ),
        ("promo", "0003_alter_merchapplication_ambassador_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouppurposeprogramstatusbase",
            name="name",
        ),
        migrations.RenameField(
            model_name="ambassador",
            old_name="onbording_status",
            new_name="onboarding_status",
        ),
        migrations.AddField(
            model_name="ambassador",
            name="personal_purpose",
            field=models.TextField(
                blank=True, null=True, verbose_name="Моя цель в Практикуме"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="name",
            field=models.CharField(
                default=1, max_length=75, verbose_name="Название группы"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="name",
            field=models.CharField(
                default=1, max_length=75, verbose_name="Программа в Практикуме"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purpose",
            name="name",
            field=models.CharField(
                default=1, max_length=75, verbose_name="Цель в Практикуме"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="name",
            field=models.CharField(default=1, max_length=75, verbose_name="Статус"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=50, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=50, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=6, verbose_name="Индекс"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=50, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="about_me",
            field=models.TextField(blank=True, null=True, verbose_name="О себе"),
        ),
        migrations.RemoveField(
            model_name="ambassador",
            name="activity",
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.address",
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="blog_link",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Ссылка на блог"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="clothing_size",
            field=models.CharField(
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                ],
                max_length=2,
                verbose_name="Размер одежды",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="education",
            field=models.CharField(max_length=120, verbose_name="Образование"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="email",
            field=models.EmailField(max_length=30, verbose_name="e=Mail"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="gender",
            field=models.CharField(
                choices=[("М", "Мужской"), ("Ж", "Женский")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.group",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="job",
            field=models.CharField(max_length=120, verbose_name="Место работы"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="name",
            field=models.CharField(max_length=50, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.program",
                verbose_name="Программа в Практикуме",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="promo.promocode",
                verbose_name="Промокод",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="purpose",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.purpose",
                verbose_name="Цель в Практикуме",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="shoe_size",
            field=models.CharField(max_length=4, verbose_name="Размер обуви"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="telegram_id",
            field=models.CharField(max_length=30, verbose_name="Telegram"),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Наставник",
            ),
        ),
        migrations.AlterField(
            model_name="ambassador",
            name="whatsapp",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="Whatsapp"
            ),
        ),
        migrations.AlterField(
            model_name="grouppurposeprogramstatusbase",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="purpose",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Moя цель в Практикуме"
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "grouppurposeprogramstatusbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ambassadors.grouppurposeprogramstatusbase",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=75, verbose_name="Цель Амбассадорства"),
                ),
            ],
            options={
                "verbose_name": "Активность",
                "verbose_name_plural": "Активности",
            },
            bases=("ambassadors.grouppurposeprogramstatusbase",),
        ),
        migrations.CreateModel(
            name="AmbassadorActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassadors.ambassador",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassadors.activity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ambassador",
            name="activity",
            field=models.ManyToManyField(
                related_name="ambassadors",
                through="ambassadors.AmbassadorActivity",
                to="ambassadors.activity",
                verbose_name="Цель Амбассадорства",
            ),
        ),
    ]
