# Generated by Django 5.0.2 on 2024-03-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0003_alter_ambassador_onboarding_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassador",
            name="purpose",
        ),
        migrations.CreateModel(
            name="AmbassadorPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassadors.ambassador",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ambassadors.purpose",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ambassador",
            name="purpose",
            field=models.ManyToManyField(
                related_name="ambassadors",
                through="ambassadors.AmbassadorPurpose",
                to="ambassadors.purpose",
                verbose_name="Цель в Практикуме",
            ),
        ),
    ]
