# Generated by Django 5.0.2 on 2024-03-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0003_remove_grouppurposeprogramstatusbase_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassador",
            name="promocode",
        ),
    ]
