# Generated by Django 5.0.2 on 2024-03-06 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0004_remove_ambassador_promocode"),
        ("promo", "0004_remove_merchapplication_ambassador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassador",
            name="promocode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="promo.promocode",
                verbose_name="Промокод",
            ),
        ),
    ]
