# Generated by Django 5.0.2 on 2024-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0004_remove_ambassador_purpose_ambassadorpurpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassador",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
