# Generated by Django 5.0.2 on 2024-03-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0004_remove_ambassador_promocode_delete_ambassadormerch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambassador",
            name="email",
            field=models.EmailField(max_length=30, verbose_name="Email"),
        ),
    ]
