# Generated by Django 5.0.2 on 2024-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0005_ambassador_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purpose",
            name="personal_purpose",
        ),
        migrations.AddField(
            model_name="ambassadorpurpose",
            name="personal_purpose",
            field=models.TextField(
                blank=True, null=True, verbose_name="Moя цель в Практикуме"
            ),
        ),
    ]
