# Generated by Django 5.0.2 on 2024-03-11 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0005_ambassador_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassador",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="purpose",
            name="personal_purpose",
        ),
        migrations.AddField(
            model_name="ambassador",
            name="personal_purpose",
            field=models.TextField(
                blank=True, null=True, verbose_name="Персональная цель в Практикуме"
            ),
        ),
        migrations.DeleteModel(
            name="AmbassadorPurpose",
        ),
        migrations.AddField(
            model_name="ambassador",
            name="purpose",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ambassadors",
                to="ambassadors.purpose",
                verbose_name="Цель в Практикуме",
            ),
        ),
    ]
