# Generated by Django 5.0.2 on 2024-03-06 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0005_ambassador_promocode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambassador",
            name="promocode",
        ),
    ]
