name: hackathon_yandex_ambassadors workflow

on:
  push:
    branches:

jobs:

  flake8_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Send start message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }} started!

            Repository: ${{ github.repository }}.
            Branch name: ${{ github.ref_name }}.
            Commit author: ${{ github.actor }}.
            Commit message: ${{ github.event.commits[0].message }}.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt

      - name: Test with flake8
        run: |
          cd src
          python -m flake8

      - name: Send success message
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }} completed successfully!

            Repository: ${{ github.repository }}.
            Branch name: ${{ github.ref_name }}.
            Commit author: ${{ github.actor }}.
            Commit message: ${{ github.event.commits[0].message }}.
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: flake8_and_tests
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hackathon_yandex_crm:v.01

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.HOST_USER_PASSWORD }} | sudo -S docker compose stop
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hackathon_yandex_crm:v.01
            touch .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} > .env
            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            echo MODE=${{ secrets.MODE }} >> .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo DOCKER=${{ secrets.DOCKER }} >> .env
            echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
            echo CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }} >> .env
            touch priv_key
            echo ${{ secrets.SSH_KEY }} > priv_key
            echo ${{ secrets.HOST_USER_PASSWORD }} | sudo -S docker compose up -d
            echo ${{ secrets.HOST_USER_PASSWORD }} | sudo -S docker image prune -f
  
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }} completed successfully!
            Repository: ${{ github.repository }}.
            Branch name: ${{ github.ref_name }}.
            Commit author: ${{ github.actor }}.
            Commit message: ${{ github.event.commits[0].message }}.
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
